"""extract bank accounts

Revision ID: 1f81cb280374
Revises: c55032509cef
Create Date: 2026-03-22 19:58:06.750313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f81cb280374'
down_revision: Union[str, Sequence[str], None] = 'c55032509cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=False),
    sa.Column('account_holder_name', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_user_id'), 'bank_accounts', ['user_id'], unique=False)
    op.drop_column('users', 'bank_ifsc_code')
    op.drop_column('users', 'bank_account_holder_name')
    op.drop_column('users', 'bank_account_number')
    op.drop_column('users', 'bank_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bank_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bank_account_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bank_account_holder_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bank_ifsc_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bank_accounts_user_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
