"""Add total_cost_basis to brick_holdings

Revision ID: 265149aef7ca
Revises: 5f6a7b8c9d0e
Create Date: 2026-04-26 11:41:03.134282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265149aef7ca'
down_revision: Union[str, Sequence[str], None] = '5f6a7b8c9d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add column as nullable or with a server default
    op.add_column('brick_holdings', sa.Column('total_cost_basis', sa.Numeric(precision=20, scale=2), nullable=False, server_default='0'))
    # Step 2: Remove the server default so it doesn't apply to future null inserts (though app logic should handle it)
    op.alter_column('brick_holdings', 'total_cost_basis', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brick_holdings', 'total_cost_basis')
    # ### end Alembic commands ###
