"""add kyc queue and audit fields

Revision ID: 2679f7e6614f
Revises: ed744dd3dbc1
Create Date: 2026-04-01 14:22:42.069368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2679f7e6614f'
down_revision: Union[str, Sequence[str], None] = 'ed744dd3dbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc_records', sa.Column('assigned_admin_id', sa.UUID(), nullable=True))
    op.add_column('kyc_records', sa.Column('reviewed_by_id', sa.UUID(), nullable=True))
    op.add_column('kyc_records', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('kyc_records', sa.Column('pan_image_url', sa.String(length=500), nullable=True))
    op.add_column('kyc_records', sa.Column('aadhaar_front_url', sa.String(length=500), nullable=True))
    op.add_column('kyc_records', sa.Column('aadhaar_back_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_kyc_records_assigned_admin_id'), 'kyc_records', ['assigned_admin_id'], unique=False)
    op.create_foreign_key(None, 'kyc_records', 'users', ['assigned_admin_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'kyc_records', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kyc_records', type_='foreignkey')
    op.drop_constraint(None, 'kyc_records', type_='foreignkey')
    op.drop_index(op.f('ix_kyc_records_assigned_admin_id'), table_name='kyc_records')
    op.drop_column('kyc_records', 'aadhaar_back_url')
    op.drop_column('kyc_records', 'aadhaar_front_url')
    op.drop_column('kyc_records', 'pan_image_url')
    op.drop_column('kyc_records', 'reviewed_at')
    op.drop_column('kyc_records', 'reviewed_by_id')
    op.drop_column('kyc_records', 'assigned_admin_id')
    # ### end Alembic commands ###
