"""Add revenue distribution models

Revision ID: 2920e783bd5a
Revises: dc5469ad199a
Create Date: 2026-04-22 17:38:30.896955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2920e783bd5a'
down_revision: Union[str, Sequence[str], None] = 'dc5469ad199a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('security_deposit', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('projects', sa.Column('estimated_monthly_rental', sa.DECIMAL(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'estimated_monthly_rental')
    op.drop_column('projects', 'security_deposit')
    # ### end Alembic commands ###
