"""add_total_escrow_held_to_project

Revision ID: 307318c37733
Revises: 2547eb561843
Create Date: 2026-04-21 19:51:09.088520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307318c37733'
down_revision: Union[str, Sequence[str], None] = '2547eb561843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('total_escrow_held', sa.DECIMAL(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'total_escrow_held')
    # ### end Alembic commands ###
