"""Add KYC records table

Revision ID: 38edb488f191
Revises: b564988e10a8
Create Date: 2026-03-14 21:06:33.040697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38edb488f191'
down_revision: Union[str, Sequence[str], None] = 'b564988e10a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kyc_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('aadhaar_hash', sa.String(length=256), nullable=True),
    sa.Column('aadhaar_last_4_digits', sa.String(length=4), nullable=True),
    sa.Column('aadhaar_verified', sa.Boolean(), nullable=True),
    sa.Column('aadhaar_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('pan_verified', sa.Boolean(), nullable=True),
    sa.Column('pan_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_sent_count', sa.Integer(), nullable=True),
    sa.Column('otp_verified_count', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_records_pan_number'), 'kyc_records', ['pan_number'], unique=True)
    op.create_index(op.f('ix_kyc_records_status'), 'kyc_records', ['status'], unique=False)
    op.create_index(op.f('ix_kyc_records_user_id'), 'kyc_records', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_records_user_id'), table_name='kyc_records')
    op.drop_index(op.f('ix_kyc_records_status'), table_name='kyc_records')
    op.drop_index(op.f('ix_kyc_records_pan_number'), table_name='kyc_records')
    op.drop_table('kyc_records')
    # ### end Alembic commands ###
