"""add_builder_wallet_and_transaction_flag

Revision ID: 3bedbecb4b61
Revises: 307318c37733
Create Date: 2026-04-21 20:10:28.580070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bedbecb4b61'
down_revision: Union[str, Sequence[str], None] = '307318c37733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builders', sa.Column('wallet_balance', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('wallet_transactions', sa.Column('is_builder_transaction', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_wallet_transactions_is_builder_transaction'), 'wallet_transactions', ['is_builder_transaction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_is_builder_transaction'), table_name='wallet_transactions')
    op.drop_column('wallet_transactions', 'is_builder_transaction')
    op.drop_column('builders', 'wallet_balance')
    # ### end Alembic commands ###
