"""Add builders table

Revision ID: 406219c0a6e9
Revises: 38edb488f191
Create Date: 2026-03-20 12:53:37.137475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406219c0a6e9'
down_revision: Union[str, Sequence[str], None] = '38edb488f191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_registration_number', sa.String(length=100), nullable=True),
    sa.Column('rera_registration_number', sa.String(length=100), nullable=True),
    sa.Column('rera_approved', sa.Boolean(), nullable=True),
    sa.Column('rera_approved_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('headquarters_address', sa.String(), nullable=True),
    sa.Column('headquarters_city', sa.String(length=100), nullable=True),
    sa.Column('headquarters_state', sa.String(length=100), nullable=True),
    sa.Column('headquarters_pincode', sa.String(length=10), nullable=True),
    sa.Column('year_established', sa.Integer(), nullable=True),
    sa.Column('total_projects_count', sa.Integer(), nullable=True),
    sa.Column('completed_projects_count', sa.Integer(), nullable=True),
    sa.Column('ongoing_projects_count', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=True),
    sa.Column('default_rate', sa.Float(), nullable=True),
    sa.Column('total_funding_raised', sa.Float(), nullable=True),
    sa.Column('total_construction_cost', sa.Float(), nullable=True),
    sa.Column('document_verified', sa.Boolean(), nullable=True),
    sa.Column('documents_verified_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_registration_number'),
    sa.UniqueConstraint('rera_registration_number')
    )
    op.create_index(op.f('ix_builders_id'), 'builders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_builders_id'), table_name='builders')
    op.drop_table('builders')
    # ### end Alembic commands ###
