"""Add purpose and payload to otps table

Revision ID: 4af83e598bb1
Revises: b97adef8989b
Create Date: 2026-05-01 15:38:22.290866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af83e598bb1'
down_revision: Union[str, Sequence[str], None] = 'b97adef8989b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('purpose', sa.String(length=50), nullable=False))
    op.add_column('otps', sa.Column('payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'payload')
    op.drop_column('otps', 'purpose')
    # ### end Alembic commands ###
