"""empty message

Revision ID: 885a4e83af6c
Revises: 976a1a5cacc8
Create Date: 2026-04-25 21:54:43.150808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885a4e83af6c'
down_revision: Union[str, Sequence[str], None] = '976a1a5cacc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_candles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('high_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('low_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('close_price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'date', name='uq_daily_candle_project_date')
    )
    op.create_index(op.f('ix_daily_candles_date'), 'daily_candles', ['date'], unique=False)
    op.create_index(op.f('ix_daily_candles_id'), 'daily_candles', ['id'], unique=False)
    op.create_index(op.f('ix_daily_candles_project_id'), 'daily_candles', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_candles_project_id'), table_name='daily_candles')
    op.drop_index(op.f('ix_daily_candles_id'), table_name='daily_candles')
    op.drop_index(op.f('ix_daily_candles_date'), table_name='daily_candles')
    op.drop_table('daily_candles')
    # ### end Alembic commands ###
