"""EstateX Exchange Models

Revision ID: 8f722f61c41f
Revises: 949a3bd570b9
Create Date: 2026-03-22 18:25:23.510062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f722f61c41f'
down_revision: Union[str, Sequence[str], None] = '949a3bd570b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brick_holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brick_holdings_id'), 'brick_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_brick_holdings_project_id'), 'brick_holdings', ['project_id'], unique=False)
    op.create_index(op.f('ix_brick_holdings_user_id'), 'brick_holdings', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('price_per_brick', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unfilled_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_type'), 'orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_orders_project_id'), 'orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('buy_order_id', sa.UUID(), nullable=False),
    sa.Column('sell_order_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buy_order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sell_order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_executed_at'), 'trades', ['executed_at'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_project_id'), 'trades', ['project_id'], unique=False)
    op.add_column('projects', sa.Column('total_bricks', sa.Integer(), server_default='1000', nullable=False))
    op.add_column('projects', sa.Column('face_value', sa.DECIMAL(precision=18, scale=2), server_default='100.00', nullable=False))
    op.add_column('projects', sa.Column('ipo_price', sa.DECIMAL(precision=18, scale=2), server_default='100.00', nullable=False))
    op.add_column('projects', sa.Column('market_value', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('projects', sa.Column('previous_close_price', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('projects', sa.Column('ipo_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_projects_ipo_status'), 'projects', ['ipo_status'], unique=False)
    op.drop_column('projects', 'funding_target')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('funding_target', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_projects_ipo_status'), table_name='projects')
    op.drop_column('projects', 'ipo_status')
    op.drop_column('projects', 'previous_close_price')
    op.drop_column('projects', 'market_value')
    op.drop_column('projects', 'ipo_price')
    op.drop_column('projects', 'face_value')
    op.drop_column('projects', 'total_bricks')
    op.drop_index(op.f('ix_trades_project_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_executed_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_project_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_type'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_brick_holdings_user_id'), table_name='brick_holdings')
    op.drop_index(op.f('ix_brick_holdings_project_id'), table_name='brick_holdings')
    op.drop_index(op.f('ix_brick_holdings_id'), table_name='brick_holdings')
    op.drop_table('brick_holdings')
    # ### end Alembic commands ###
