"""add_execution_type_to_orders

Revision ID: 8f98c8aa02b9
Revises: 265149aef7ca
Create Date: 2026-04-26 13:34:54.508449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f98c8aa02b9'
down_revision: Union[str, Sequence[str], None] = '265149aef7ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('execution_type', sa.String(length=20), nullable=True))
    op.execute("UPDATE orders SET execution_type = 'limit'")
    op.alter_column('orders', 'execution_type', nullable=False)
    
    op.alter_column('orders', 'price_per_brick',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'price_per_brick',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    op.drop_column('orders', 'execution_type')
    # ### end Alembic commands ###
