"""add_investment_preference_to_users

Revision ID: 90bd4cb26bee
Revises: 8f98c8aa02b9
Create Date: 2026-04-27 15:18:13.481714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90bd4cb26bee'
down_revision: Union[str, Sequence[str], None] = '8f98c8aa02b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_project_holding', 'brick_holdings', ['user_id', 'project_id'])
    op.add_column('users', sa.Column('investment_preference', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'investment_preference')
    op.drop_constraint('uq_user_project_holding', 'brick_holdings', type_='unique')
    # ### end Alembic commands ###
