"""User Wallet Balance Fix

Revision ID: 949a3bd570b9
Revises: 26d6061f685a
Create Date: 2026-03-20 14:23:05.887917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949a3bd570b9'
down_revision: Union[str, Sequence[str], None] = '26d6061f685a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_balance', sa.DECIMAL(precision=18, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_balance')
    # ### end Alembic commands ###
