"""Add rental cycle and payout tables

Revision ID: 96fcac300a57
Revises: 2920e783bd5a
Create Date: 2026-04-22 17:47:19.031153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fcac300a57'
down_revision: Union[str, Sequence[str], None] = '2920e783bd5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rental_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('fee_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_cycles_id'), 'rental_cycles', ['id'], unique=False)
    op.create_index(op.f('ix_rental_cycles_project_id'), 'rental_cycles', ['project_id'], unique=False)
    op.create_index(op.f('ix_rental_cycles_status'), 'rental_cycles', ['status'], unique=False)
    op.create_table('rental_payouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('eligible_quantity', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['rental_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_payouts_cycle_id'), 'rental_payouts', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_rental_payouts_id'), 'rental_payouts', ['id'], unique=False)
    op.create_index(op.f('ix_rental_payouts_user_id'), 'rental_payouts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_payouts_user_id'), table_name='rental_payouts')
    op.drop_index(op.f('ix_rental_payouts_id'), table_name='rental_payouts')
    op.drop_index(op.f('ix_rental_payouts_cycle_id'), table_name='rental_payouts')
    op.drop_table('rental_payouts')
    op.drop_index(op.f('ix_rental_cycles_status'), table_name='rental_cycles')
    op.drop_index(op.f('ix_rental_cycles_project_id'), table_name='rental_cycles')
    op.drop_index(op.f('ix_rental_cycles_id'), table_name='rental_cycles')
    op.drop_table('rental_cycles')
    # ### end Alembic commands ###
