"""add_wallet_balance_non_negative_constraints

Revision ID: 976a1a5cacc8
Revises: 96fcac300a57
Create Date: 2026-04-25 21:10:06.060698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976a1a5cacc8'
down_revision: Union[str, Sequence[str], None] = '96fcac300a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
