"""Add MacroAnalytics table

Revision ID: 9d786607817d
Revises: cdeaa4c032f4
Create Date: 2026-04-22 15:09:05.421433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d786607817d'
down_revision: Union[str, Sequence[str], None] = 'cdeaa4c032f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pincode', sa.String(), nullable=False),
    sa.Column('yoy_growth_percentage', sa.Float(), nullable=False),
    sa.Column('avg_rental_yield', sa.Float(), nullable=False),
    sa.Column('demand_score', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_analytics_pincode'), 'macro_analytics', ['pincode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_macro_analytics_pincode'), table_name='macro_analytics')
    op.drop_table('macro_analytics')
    # ### end Alembic commands ###
