"""Add full user profile schema

Revision ID: c55032509cef
Revises: 8f722f61c41f
Create Date: 2026-03-22 19:51:54.077549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55032509cef'
down_revision: Union[str, Sequence[str], None] = '8f722f61c41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('kyc_rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('account_type', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('bank_account_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('bank_ifsc_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('bank_account_holder_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('bank_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('wallet_address', sa.String(length=66), nullable=True))
    op.add_column('users', sa.Column('notification_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notification_sms', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notification_push', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('ip_address_created', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'users', ['wallet_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'ip_address_created')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'language')
    op.drop_column('users', 'notification_push')
    op.drop_column('users', 'notification_sms')
    op.drop_column('users', 'notification_email')
    op.drop_column('users', 'wallet_address')
    op.drop_column('users', 'bank_verified')
    op.drop_column('users', 'bank_account_holder_name')
    op.drop_column('users', 'bank_ifsc_code')
    op.drop_column('users', 'bank_account_number')
    op.drop_column('users', 'two_factor_enabled')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'account_type')
    op.drop_column('users', 'kyc_rejection_reason')
    op.drop_column('users', 'kyc_verified_at')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
