"""Add detailed builder profile and document fields

Revision ID: cbc236003348
Revises: f7547e6a8210
Create Date: 2026-04-22 11:48:33.249156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc236003348'
down_revision: Union[str, Sequence[str], None] = 'f7547e6a8210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builders', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('builders', sa.Column('pan_number', sa.String(length=20), nullable=True))
    op.add_column('builders', sa.Column('gst_number', sa.String(length=20), nullable=True))
    op.add_column('builders', sa.Column('reg_cert_url', sa.String(length=500), nullable=True))
    op.add_column('builders', sa.Column('balance_sheet_url', sa.String(length=500), nullable=True))
    op.add_column('builders', sa.Column('it_returns_url', sa.String(length=500), nullable=True))
    op.add_column('builders', sa.Column('bank_statements_url', sa.String(length=500), nullable=True))
    op.add_column('builders', sa.Column('rera_cert_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('builders', 'rera_cert_url')
    op.drop_column('builders', 'bank_statements_url')
    op.drop_column('builders', 'it_returns_url')
    op.drop_column('builders', 'balance_sheet_url')
    op.drop_column('builders', 'reg_cert_url')
    op.drop_column('builders', 'gst_number')
    op.drop_column('builders', 'pan_number')
    op.drop_column('builders', 'business_type')
    # ### end Alembic commands ###
