"""add_property_spec_fields

Revision ID: cdeaa4c032f4
Revises: cbc236003348
Create Date: 2026-04-22 12:43:01.406311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdeaa4c032f4'
down_revision: Union[str, Sequence[str], None] = 'cbc236003348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('property_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('bedroom_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('bathroom_count', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('area_sqft', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'area_sqft')
    op.drop_column('projects', 'bathroom_count')
    op.drop_column('projects', 'bedroom_count')
    op.drop_column('projects', 'property_type')
    # ### end Alembic commands ###
