"""Add governance and voting tables

Revision ID: dc5469ad199a
Revises: 9d786607817d
Create Date: 2026-04-22 16:22:02.664221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc5469ad199a'
down_revision: Union[str, Sequence[str], None] = '9d786607817d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_option_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_proposals_id'), 'governance_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_governance_proposals_project_id'), 'governance_proposals', ['project_id'], unique=False)
    op.create_index(op.f('ix_governance_proposals_status'), 'governance_proposals', ['status'], unique=False)
    op.create_table('proposal_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('option_index', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['governance_proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_votes_id'), 'proposal_votes', ['id'], unique=False)
    op.create_index(op.f('ix_proposal_votes_proposal_id'), 'proposal_votes', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_proposal_votes_user_id'), 'proposal_votes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposal_votes_user_id'), table_name='proposal_votes')
    op.drop_index(op.f('ix_proposal_votes_proposal_id'), table_name='proposal_votes')
    op.drop_index(op.f('ix_proposal_votes_id'), table_name='proposal_votes')
    op.drop_table('proposal_votes')
    op.drop_index(op.f('ix_governance_proposals_status'), table_name='governance_proposals')
    op.drop_index(op.f('ix_governance_proposals_project_id'), table_name='governance_proposals')
    op.drop_index(op.f('ix_governance_proposals_id'), table_name='governance_proposals')
    op.drop_table('governance_proposals')
    # ### end Alembic commands ###
