"""Add extended project details

Revision ID: ed744dd3dbc1
Revises: 1f81cb280374
Create Date: 2026-03-22 20:04:59.403447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed744dd3dbc1'
down_revision: Union[str, Sequence[str], None] = '1f81cb280374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('rera_approved', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('environmental_clearance', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('insurance_coverage', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('launch_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('construction_start_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('rera_approval_url', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('brochure_url', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('floor_plans', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('projects', sa.Column('funding_target', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('projects', sa.Column('min_investment', sa.DECIMAL(precision=18, scale=2), nullable=True))
    op.add_column('projects', sa.Column('investor_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'view_count')
    op.drop_column('projects', 'investor_count')
    op.drop_column('projects', 'min_investment')
    op.drop_column('projects', 'funding_target')
    op.drop_column('projects', 'images')
    op.drop_column('projects', 'floor_plans')
    op.drop_column('projects', 'brochure_url')
    op.drop_column('projects', 'rera_approval_url')
    op.drop_column('projects', 'construction_start_date')
    op.drop_column('projects', 'launch_date')
    op.drop_column('projects', 'insurance_coverage')
    op.drop_column('projects', 'environmental_clearance')
    op.drop_column('projects', 'rera_approved')
    op.drop_column('projects', 'longitude')
    op.drop_column('projects', 'latitude')
    # ### end Alembic commands ###
