"""Add builder bank details

Revision ID: f7547e6a8210
Revises: 3bedbecb4b61
Create Date: 2026-04-22 11:22:49.630428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7547e6a8210'
down_revision: Union[str, Sequence[str], None] = '3bedbecb4b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builders', sa.Column('bank_account_name', sa.String(length=255), nullable=True))
    op.add_column('builders', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('builders', sa.Column('bank_account_number', sa.String(length=100), nullable=True))
    op.add_column('builders', sa.Column('bank_ifsc_code', sa.String(length=20), nullable=True))
    op.alter_column('builders', 'wallet_balance',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('builders', 'wallet_balance',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.drop_column('builders', 'bank_ifsc_code')
    op.drop_column('builders', 'bank_account_number')
    op.drop_column('builders', 'bank_name')
    op.drop_column('builders', 'bank_account_name')
    # ### end Alembic commands ###
